package advising;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change tthis template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.util.ArrayList;
import java.awt.Color;
import javax.swing.ButtonGroup;

/**
 *
 * @author 
 */
public class HomePage extends javax.swing.JFrame {

    /**
     *
     */
    private static final long serialVersionUID = 5178702100512213267L;

    /**
     * Creates new form HomePage
     */
    private ArrayList<String> courses;
    private Student student;
    private AdvisingAgent adviser;

    public HomePage(AdvisingAgent agent){
        adviser = agent;
        initComponents();
        ButtonGroup buttonGroup = new ButtonGroup();
        buttonGroup.add(sem1Button);
        buttonGroup.add(sem2Button);

        //These can buttons can be deleted. 
        level2Prompt.setVisible(false);
        yesButton.setVisible(false);
        noButton.setVisible(false);
    }

    public HomePage(){}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        dctiLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        idLabel = new javax.swing.JLabel();
        idField = new javax.swing.JTextField();
        sem1Button = new javax.swing.JRadioButton();
        semesterLabel = new javax.swing.JLabel();
        sem2Button = new javax.swing.JRadioButton();
        degreeCombo = new javax.swing.JComboBox<>();
        degreeLabel = new javax.swing.JLabel();
        gpaLabel = new javax.swing.JLabel();
        gpaField = new javax.swing.JTextField();
        yearLabel = new javax.swing.JLabel();
        yearComboBox = new javax.swing.JComboBox<>();
        level1Choices = new javax.swing.JPanel();
        choiceLabel = new javax.swing.JLabel();
        comp1600 = new javax.swing.JRadioButton();
        comp1601 = new javax.swing.JRadioButton();
        comp1602 = new javax.swing.JRadioButton();
        math1115 = new javax.swing.JRadioButton();
        comp1603 = new javax.swing.JRadioButton();
        comp1604 = new javax.swing.JRadioButton();
        info1600 = new javax.swing.JRadioButton();
        info1601 = new javax.swing.JRadioButton();
        level2Prompt = new javax.swing.JLabel();
        yesButton = new javax.swing.JRadioButton();
        noButton = new javax.swing.JRadioButton();
        advisingButton = new javax.swing.JButton();
        coursesButton = new javax.swing.JButton();
        displayPanel = new javax.swing.JScrollPane();
        display = new javax.swing.JTextArea();

        courses = new ArrayList<String>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        sem1Button.setSelected(true);
        dctiLabel.setText("DCIT ACADEMIC ADVISING ");
        dctiLabel.setSize(new java.awt.Dimension(76, 28));

        nameLabel.setText("NAME");

        nameField.setText("");
        nameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFieldActionPerformed(evt);
            }
        });

        idLabel.setText("STUDENT ID");

        idField.setText("");
        idField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idFieldActionPerformed(evt);
            }
        });

        sem1Button.setText("Semester 1");
        sem1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sem1ButtonActionPerformed(evt);
            }
        });

        semesterLabel.setText("SEMESTER");

        sem2Button.setText("Semester 2");

        degreeCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                degreeComboActionPerformed(evt);
            }
        });

        degreeLabel.setText("DEGREE");
        gpaLabel.setText("GPA");
        gpaField.setText("  ");
        yearLabel.setText("YEAR");
        yearComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"Year 2" }));
        degreeCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"BSc. Computer Science (Special)","BSc. Information Technology (Special)"}));
        choiceLabel.setText("Please select the Level I courses that were sucessfully completed:");

        comp1600.setText("COMP 1600");
        comp1600.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comp1600ActionPerformed(evt);
            }
        });

        comp1601.setText("COMP 1601");
        comp1601.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comp1601ActionPerformed(evt);
            }
        });

        comp1602.setText("COMP 1602");
        comp1602.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comp1602ActionPerformed(evt);
            }
        });

        math1115.setText("MATH 1115");
        math1115.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                math1115ActionPerformed(evt);
            }
        });

        comp1603.setText("COMP 1603");
        comp1604.setText("COMP 1604");
        info1600.setText("INFO 1600");
        info1601.setText("INFO 1601");
        level2Prompt.setText("Have you sucessfully completed any Level II Courses? ");
        yesButton.setText("Yes");

        yesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesButtonActionPerformed(evt);
            }
        });

        noButton.setText("No");

        advisingButton.setText("Get Advising");
        advisingButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                advisingButtonMouseClicked(evt);
            }
        });

        coursesButton.setText("Get Courses");
        coursesButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                coursesButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout level1ChoicesLayout = new javax.swing.GroupLayout(level1Choices);
        level1Choices.setLayout(level1ChoicesLayout);
        level1ChoicesLayout.setHorizontalGroup(
            level1ChoicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(level1ChoicesLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(level1ChoicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(comp1601)
                    .addComponent(comp1600)
                    .addComponent(comp1602)
                    .addComponent(comp1603))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(level1ChoicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comp1604)
                    .addComponent(info1600)
                    .addComponent(info1601)
                    .addComponent(math1115))
                .addGap(46, 46, 46))
            .addGroup(level1ChoicesLayout.createSequentialGroup()
                .addGroup(level1ChoicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(level1ChoicesLayout.createSequentialGroup()
                        .addComponent(level2Prompt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(yesButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(noButton))
                    .addComponent(choiceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(level1ChoicesLayout.createSequentialGroup()
                    .addGap(110, 110, 110)
                    .addComponent(coursesButton)
                    //.addGap(159, 159, 159)
                        .addComponent(advisingButton)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        level1ChoicesLayout.setVerticalGroup(
            level1ChoicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(level1ChoicesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(choiceLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(level1ChoicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comp1600)
                    .addComponent(comp1604))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(level1ChoicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comp1601)
                    .addComponent(info1600))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(level1ChoicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comp1602)
                    .addComponent(info1601))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(level1ChoicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(comp1603)
                .addComponent(math1115))
                .addGap(12, 12, 12)
                .addGroup(level1ChoicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(level2Prompt)
                    .addComponent(yesButton)
                    .addComponent(noButton))
                .addGap(13, 13, 13)
                .addGroup(level1ChoicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(coursesButton)
                .addComponent(advisingButton))
            )
        );

        display.setColumns(20);
        display.setRows(5);
        displayPanel.setViewportView(display);

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(level1Choices, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(dctiLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(129, 129, 129))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelLayout.createSequentialGroup()
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelLayout.createSequentialGroup()
                                        .addComponent(semesterLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(sem1Button)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(sem2Button)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(yearLabel))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelLayout.createSequentialGroup()
                                        .addComponent(nameLabel)
                                        .addGap(3, 3, 3)
                                        .addComponent(nameField, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                                        .addGap(61, 61, 61)
                                        .addComponent(idLabel)))
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(idField, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(yearComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelLayout.createSequentialGroup()
                                .addComponent(degreeLabel)
                                .addGap(3, 3, 3)
                                .addComponent(degreeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(gpaLabel)
                                .addGap(3, 3, 3)
                                .addComponent(gpaField, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(displayPanel))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(dctiLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idLabel)
                    .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sem1Button)
                    .addComponent(semesterLabel)
                    .addComponent(sem2Button)
                    .addComponent(yearLabel)
                    .addComponent(yearComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(degreeLabel)
                    .addComponent(degreeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gpaLabel)
                    .addComponent(gpaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(level1Choices, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(displayPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(242, 242, 242))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 549, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFieldActionPerformed
        
    }//GEN-LAST:event_nameFieldActionPerformed

    private void idFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idFieldActionPerformed
        
    }//GEN-LAST:event_idFieldActionPerformed

    private void sem1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sem1ButtonActionPerformed
       
    }//GEN-LAST:event_sem1ButtonActionPerformed

    private void comp1602ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comp1602ActionPerformed
       
    }//GEN-LAST:event_comp1602ActionPerformed

    private void math1115ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comp1602ActionPerformed
       
    }//GEN-LAST:event_comp1602ActionPerformed

    private void comp1600ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comp1600ActionPerformed
       
    }//GEN-LAST:event_comp1600ActionPerformed

    private void yesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesButtonActionPerformed
        
    }//GEN-LAST:event_yesButtonActionPerformed

    private void comp1601ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comp1601ActionPerformed
        
    }//GEN-LAST:event_comp1601ActionPerformed

    private void degreeComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_degreeComboActionPerformed
        
    }//GEN-LAST:event_degreeComboActionPerformed
    private void coursesButtonMouseClicked(java.awt.event.MouseEvent evt){
        CourseList courseList = new CourseList();
        courseList.setVisible(true);
    }

    /* This Method extracts the student information from the gui and creates the student 
        The adviseStudent method of the Facade gets the recommended list of courses which is printed to the JPanel
        The functionality works, the code is however pulling course information from the wrong place
        
        I also changed the generic type of coursesCompleted ArrayList in the Student class from Course to String 
 */
    private void advisingButtonMouseClicked(java.awt.event.MouseEvent evt) {
        if(comp1600.isSelected()){
            courses.add("COMP1600");
        }
        
        if (comp1601.isSelected()){
            courses.add("COMP1601");
        }
        
        if(comp1602.isSelected()){
            courses.add("COMP1602");
        }

        if(math1115.isSelected()){
            courses.add("MATH1115");
        }
        
        if(comp1603.isSelected()){
            courses.add("COMP1603");
        }
        
        if(comp1604.isSelected()){
            courses.add("COMP1604");
        }
        
        if(info1600.isSelected()){
            courses.add("INFO1600");
        }
        
        if(info1601.isSelected()){
            courses.add("INFO1601");
        }
        

        String name = nameField.getText();
        String id = idField.getText();
        String currSem = "1";
        if(sem1Button.isSelected())
            currSem = "1";
        if(sem2Button.isSelected())
            currSem = "2"; 
        String currYear = "2";
        String degree = degreeCombo.getSelectedItem().toString(); 
        double gpa = Double.valueOf(getGPADouble());
        student = new Student(id, name, currSem, currYear, degree, gpa, courses);

        display.setForeground(Color.black);

        if (nameField.getText().equals("") || idField.getText().equals("") || gpaField.getText().equals("")){
            display.setForeground(Color.blue);
            display.setText("Please enter all information.");
        }
        else {
        if (getGPADouble()<0){
        display.setForeground(Color.red);
        String text = adviser.adviseStudent(student) + "\nPlease contact the Department of Computing and Information Technology for further assistance.";
        display.setForeground(Color.blue);
        display.setText(text);
        display.setForeground(Color.blue);
        }
        else{
        display.setText(adviser.adviseStudent(student));
        }
        clear();
    }
    }

    private void clear(){
        comp1600.setSelected(false);
        comp1601.setSelected(false);
        comp1602.setSelected(false);
        math1115.setSelected(false);
        comp1603.setSelected(false);
        comp1604.setSelected(false);
        info1600.setSelected(false);        
        info1601.setSelected(false);
        courses.clear();
        nameField.setText("");
        idField.setText("");
        sem1Button.setSelected(true);
        degreeCombo.setSelectedIndex(0);
        yearComboBox.setSelectedIndex(0);
        gpaField.setText("");
    }

    private double getGPADouble(){
    try{
        double gpa = Double.parseDouble(gpaField.getText().strip());
        return gpa;
    }
     catch(NumberFormatException ex){
       return -1;
     }

    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);


                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel choiceLabel;
    private javax.swing.JRadioButton comp1600;
    private javax.swing.JRadioButton comp1601;
    private javax.swing.JRadioButton comp1602;
    private javax.swing.JRadioButton math1115;
    private javax.swing.JRadioButton comp1603;
    private javax.swing.JRadioButton comp1604;
    private javax.swing.JLabel dctiLabel;
    private javax.swing.JComboBox<String> degreeCombo;
    private javax.swing.JLabel degreeLabel;
    private javax.swing.JTextArea display;
    private javax.swing.JScrollPane displayPanel;
    private javax.swing.JTextField gpaField;
    private javax.swing.JLabel gpaLabel;
    private javax.swing.JTextField idField;
    private javax.swing.JLabel idLabel;
    private javax.swing.JRadioButton info1600;
    private javax.swing.JRadioButton info1601;
    private javax.swing.JPanel level1Choices;
    private javax.swing.JLabel level2Prompt;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JButton advisingButton;
    private javax.swing.JRadioButton noButton;
    private javax.swing.JPanel panel;
    private javax.swing.JRadioButton sem1Button;
    private javax.swing.JRadioButton sem2Button;
    private javax.swing.JLabel semesterLabel;
    private javax.swing.JComboBox<String> yearComboBox;
    private javax.swing.JLabel yearLabel;
    private javax.swing.JRadioButton yesButton;
    private javax.swing.JButton coursesButton;
    // End of variables declaration//GEN-END:variables
}
